import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar'
import GoogleChart from '../components/GoogleChart'
import Trade_top from '../components/Trade_top'
import Trading_down from '../components/Trading_down'

const inter = Inter({ subsets: ['latin'] })

const tradingpage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 h-max">
        <Navbar/>
        <Trade_top/>
        <GoogleChart/>
        <div className="w-screen flex justify-center items-center">
          <Trading_down/>
        </div>
      </main>
    </>
  )
}

export default tradingpage
