import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Chart from '../components/Chart'

const inter = Inter({ subsets: ['latin'] })

export default function tradingpage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <h1 class="mt-5 text-center mb-4 text-5xl font-extrabold tracking-tight leading-none text-cyan-900 ">Start predicting with <span class="text-blue-600 dark:text-blue-500">Candle sticks</span></h1>
        <Chart/>
      </main>
    </>
  )
}
